engine:
  type: "in_memory"
network:
  address: "127.0.0.1:3323"
  max_connections: 25
  max_message_size: 4096
  idle_timeout: 5m
logging:
  level: "info"
  output: "kv-db-output.log"
wal:
  flushing_batch_size: 100
  flushing_batch_timeout: 5ms
  max_segment_size: 1048576
  data_directory: "/home/pvv/wal"